language: php
php:
  - 5.5
  - 5.4
    #  - hhvm
install: true

script: phpunit Test.php

after-success:
    sshpass -p liuruifeng scp -o stricthostkeychecking=no -r ./* y@202.120.40.82:~/Downloads/
    
