language: php
php:
  - 5.5
  - 5.4
    #  - hhvm
install: true

script: phpunit Test.php

after-success:
    sshpass -p liuruifeng123 scp -o stricthostkeychecking=no -r ./* root@111.231.57.187:~/

deploy:
    sshpass -p liuruifeng123 scp -o stricthostkeychecking=no -r ./* root@111.231.57.187:~/
